% im = imread ('A-train.bmp');
im2 = imread ('A-erizka50.bmp');
% dataset_name1 = 1;
 dataset_name2 = 2;
% im = preprocessing_histo(im,dataset_name1);
im = preprocessing_histo(im2,dataset_name2);
R = im(:,:,1);
G = im(:,:,2);
B = im(:,:,3);
gs = rgb2gray(im);
level = graythresh(gs);
bw    = im2bw(gs,level);
hsv   = rgb2hsv(im);
V    = hsv(:,:,3);
ycbcr =rgb2ycbcr(im);
cr    =ycbcr(:,:,3);
% figure;
% subplot (2,2,1); imshow(im);title('Citra Dataset A');
% subplot (2,2,2); imshow(im2);title('Citra Dataset B');
% subplot (2,2,3); imhist(im); title('Histogram Dataset A');
% subplot (2,2,4); imhist(im2); title('Histogram Dataset B');
subplot(3,3,1); imshow(im);title('Gambar awal');
subplot(3,3,2); imhist(R); title('Layer Red');
subplot(3,3,3); imhist(G); title('Layer Green');
subplot(3,3,4); imhist(B); title('Layer Blue');
subplot(3,3,5); imhist(gs);title('Layer Grayscale');
subplot(3,3,6); imhist(bw);title('Layer Binary');
subplot(3,3,7); imhist(V); title('Layer HSV(V)');
subplot(3,3,8); imhist(cr);title('Layer YCbCr(Cr)');
